### ISSUE TITLE
App closed with «This screen will be closed» after 10 min

### ISSUE THREAD

**Issue by JrRadiant** [Slluxx/pokemontv#3] opened 2022-01-14 15:56 UTC
Hello!..

After 10 min program closes automatically with the «This screen will be closed» caption. What can I do to disable it?..

FW 13.2.0
AMS 1.2.5
FAT32

**Comment by Slluxx** [comment] 2022-01-14 16:57
I have never encountered that screen. Can you share a screenshot?

Edit: After running the homebrew/website and videos for 30+mins, i could not reproduce your issue.
However, clicking X (which closes the browser) or B (Which goes "back" and thus closes the browser too) showed me that screen once. Is it possible that you pressed on of those buttons on accident?

**Comment by JrRadiant** [comment] 2022-01-15 04:03
Okay, I'll test it more and try to be more careful with all the buttons.

..maybe one can use button combinations (like — and + simultaneously) to exit from the player, instead of just A or just B buttons? Thanks.

**Comment by Slluxx** [comment] 2022-01-15 04:13
`+` and `-` are buttons for browser functions. I cant remap their functionality. That said, i can not remap any functionality that comes from "inside" the browser, such as X to close or B to go back. Maybe i can work around the B problem by filling the history a few times with the same page so instead of closing the browser, it would "go back" to the previous site, which is just the same as the current.

The switchs browser is very limited and i need to do some testing with it.

**Comment by Slluxx** [comment] 2022-01-15 19:47
@JrRadiant Ive release a new version which will restart the browser if you pressed B (not X though).
its just a workaround and not my most preferred solution but it takes away a little of the annoyance

**Closed as completed** 2022-01-22 12:20 UTC
